# Generated by Django 4.2.1 on 2023-05-24 09:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channels',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False, verbose_name='channel_id')),
                ('title', models.CharField(max_length=100, verbose_name='channel_title')),
                ('views', models.IntegerField(verbose_name='channel_views')),
                ('subscribers', models.IntegerField(verbose_name='channel_subscribers')),
                ('videos_number', models.IntegerField(verbose_name='videos_number')),
                ('channel_url', models.URLField(verbose_name='channel_url')),
            ],
            options={
                'verbose_name': 'channel',
                'verbose_name_plural': 'channels',
            },
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_id', models.IntegerField(verbose_name='video_id')),
                ('title', models.TextField(verbose_name='video_title')),
                ('publish_date', models.DateTimeField(verbose_name='publish_date')),
                ('video_url', models.IntegerField(verbose_name='video_url')),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.channels', verbose_name='channel_id')),
            ],
        ),
    ]
