# Generated by Django 4.2.1 on 2023-05-24 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.URLField(verbose_name='video_url'),
        ),
    ]
