# Generated by Django 4.2.1 on 2023-05-24 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_videos_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channels',
            name='channel_url',
            field=models.URLField(max_length=255, verbose_name='channel_url'),
        ),
        migrations.AlterField(
            model_name='videos',
            name='video_url',
            field=models.URLField(max_length=255, verbose_name='video_url'),
        ),
    ]
