# Generated by Django 4.2.1 on 2023-05-24 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_channels_title_alter_videos_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='MainChannels',
            fields=[
                ('channel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=250)),
                ('views', models.IntegerField()),
                ('subscribers', models.IntegerField()),
                ('videos_number', models.IntegerField()),
                ('channel_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'main_channels',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MainVideos',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('video_id', models.IntegerField()),
                ('title', models.TextField()),
                ('publish_date', models.DateTimeField()),
                ('video_url', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'main_videos',
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='videos',
            name='channel',
        ),
        migrations.DeleteModel(
            name='Channels',
        ),
        migrations.DeleteModel(
            name='Videos',
        ),
    ]
